# Generated by Django 4.2.1 on 2023-07-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyingPrograms',
            new_name='Publications',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О сайте', 'verbose_name_plural': 'О сайте'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.CharField(db_index=True, max_length=255, verbose_name='О сайте'),
        ),
    ]
